### ISSUE TITLE
Bug: If server is offline

### ISSUE THREAD

**Issue by BarterClub** [tgxn/lemmy-explorer#128]
**Describe the bug**
When the server is having issues or is offline, the crawler thinks nothing is there and deletes the server till the next time it looks. 

**To Reproduce**
https://sh.itjust.works/c/antiwork@lemmy.fmhy.ml

The server where hosted was down for a while. Now the community is missing from the site. 

Image

https://jmp.sh/yH71a7C8

**Expected behavior**
Should skip till the next time it crawls. If there are too many skips then remove them. 

**Additional context**
The community has over 3000.

**Comment by tgxn** [comment]
I've extended the timeout for old data to appear to be 18 hours - it was 16 before.
https://github.com/tgxn/lemmy-explorer/pull/133/commits/e5b0ed6c8e82f44ee9a52a994f70745abd1daaf1

That should mean there can be two errors before instances are removed. There was another bug with error not expiring after 8 hours, which would be related.
https://github.com/tgxn/lemmy-explorer/issues/130

I've added both and pushed the fixes, 

FYI.. `fmhy.ml` was killed, so: https://sh.itjust.works/c/antiwork will no longer work, nor will `lemmy.fmhy.ml` or it's communities be shown, since the domain is dead.

I'd suggest using `https://sh.itjust.works/c/antiwork`:
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/c5d48778-c620-4663-8bac-f65344bf688d)
