### ISSUE TITLE
Bug: Instance is not listed on lemmyverse.net

### ISSUE THREAD

**Issue by Security-Chief-Odo** [tgxn/lemmy-explorer#130]
**Describe the bug**
Beehaw.org is not listed on https://lemmyverse.net/

**To Reproduce**
Go to https://lemmyverse.net/
Search for 'beehaw.org'
Get nothing found

**Expected behavior**
Go to https://lemmyverse.net/
Search for 'beehaw.org'
Beehaw.org is shown 

**Additional context**
Would like to determine why this is the case. I am a systems administrator at beehaw.org, and when I search our logs, I see successful HTTP 200's for the requested endpoints `/api/v3/community/list(params)`,  `/.well-known/nodeinfo`,  `/nodeinfo/2.0.json` and `/api/v3/site` for the user-agent  `lemmy-explorer-crawler/**`

If it has been successful, I'd like to understand why beehaw.org is not listed on lemmyverse.net as expected.

**Comment by tgxn** [comment]
Hmm, yeah there's something up, there's a bug that's not setting the redis ttl properly -.-
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/5b4dc7c0-2e41-4de0-b72e-d9c8c2431779)

So the error that I got 5 days ago `"Failed to get url https://beehaw.org/api/v3/site after 4 attempts: Request failed with status code 502",` is still stopping the crawler from trying agian.

I've manually expired and fixed the ttl's so it'll be scanned shortly. I'll see what's going on with these TTL's since they should be getting set when the error is written to redis.

**Comment by tgxn** [comment]
Update, patched bug in crawler https://github.com/tgxn/lemmy-explorer/commit/6087a1131ffba36cb034152e2463338d2984cc62#diff-4b2bdb4ce96d3bb4498017a614674143497a34bfd46e426da8e348b4c699cdadR138

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/f6c54b94-2e36-4348-9f5e-17be2216b587)

👍

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/6962d9d2-172d-43fc-9701-061899654dd4)

looking better, will get thru that instance queue at some point I'm sure :D

**Comment by 2014MU69** [comment]
Btw sh.itjust.works also isn't showing up.

**Comment by Security-Chief-Odo** [comment]
Thank you for identifying the reason and fixing it quickly!

**Comment by tgxn** [comment]
> Btw sh.itjust.works also isn't showing up.

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/f13f9931-6c3b-42a1-bc88-9fd31a8e74cc)

Showing up OK for me. Might have been caching?

**Comment by 2014MU69** [comment]
It's working now but it wasn't working for the last few days.

**Comment by tgxn** [comment]
there was another recent outage of one of the bigger instances that now seems fixed
