### ISSUE TITLE
Feature: Adjust "Endorsed" and "Blocked" Smart-Sort Ranking

### ISSUE THREAD

**Issue by daithi-coyle** [tgxn/lemmy-explorer#151]
I may be misunderstanding how smart sort works, but it seems of these two results that the second community in the list is "bigger" in every way.

<img width="1247" alt="smartsort" src="https://github.com/tgxn/lemmy-explorer/assets/36820837/157b6189-0ec2-436f-b7ba-1fb28d695a3c">

**Comment by tgxn** [comment]
lemmy.ml { linked: 150, endorsements: 24, allowed: 81 }
sh.itjust.works { linked: 133, endorsements: 16, allowed: 24, blocked: '-20' }}

it's adjusted sh.itjust.works down because there are two instances that have them on their block list

**Comment by daithi-coyle** [comment]
Thank you for your reply.

New to Lemmy have not come across endorsements or block lists yet. Lots to learn

**Comment by tgxn** [comment]
Endorsements are fetched from a service called fediseer, it's like an extra validation for trusted instances:
https://github.com/tgxn/lemmy-explorer/issues/115

By Block Lists I mean "Incoming Defederations" meaning that another instance has add them to their blocked instance list:
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/e3dd4fa0-3d0e-4213-80e4-06b3adf6e5b3)

This is something admins sometimes do to prevent bad instances content being federated to their instance.

The issue is the weighting I've assigned for these blocked lists is ten times more than I've given for good endorsed instances, I'll leave this open for a bit and make some adjustments to the weighting for these values. 👌
