### ISSUE TITLE
Provide an option to filter communities by instance (with both whitelist and blacklist modes)

### ISSUE THREAD

**Issue by ppptan** [tgxn/lemmy-explorer#35]
For example, have a searchable list containing all instances, with each list item able to be selected.  Another drop-down or checkbox allows the user to choose whether to use the selected instances as a whitelist or blacklist.

**Comment by tgxn** [comment]
I started adding a new path `/communities/INSTANNCE_ADDRESS` to filter showing communities from a specific sub.

I was planning to add a global "distrust list" and provide a different option for filtering those out, but per-instance like the Feddit site might be better.

I could re-use the "LanguageFilter" component to list/search instances (there's "only" 600)

**Comment by ppptan** [comment]
> I started adding a new path `/communities/INSTANCE_ADDRESS` to filter showing communities from a specific instance.

As in being able to see which only the communities that users of a particular instance can see?  Good idea.

**Comment by ppptan** [comment]
Another point on this is that it would be extremely useful to translate the links on `/communities/INSTANCE_ADDRESS` to viewing that community through the selected instance's website rather than through the community's home instance website.

**Comment by boomboxnation** [comment]
Adding here because I think it's just a different way to achieve what the requestor desires:

Lemmy reference: https://lemmy.ca/post/911728

It occurs to me that it would be handy if the [Lemmy Explorer](https://github.com/tgxn/lemmy-explorer) could be either run with or proxied through an individual instance providing a ‘Subscribe’ button and hiding by default unfederated instances and their communities.

The current “Search Explorer --> copy full comm URL --> Home instance Search for Federated Community --> Cross fingers and wait --> Try to subscribe” workflow is wanting IMO.

**Comment by tgxn** [comment]
@boomboxnation this is basicaally what I wanted to achieve with #5 - the issue is Lemmy CORS configurationwhich was added in https://github.com/LemmyNet/lemmy/pull/3191

Looks like it may now be possible once instances deploy updated versions. I'll re-open #5 as I was pretty excited about getting lists of people's subscriptions and allow subscribing without leaving lemmyverse

**Comment by tgxn** [comment]
This issue, is more about filtering the `/communities` list down to the ones a single instance.

I'd like to see a way to select multiple instances with a autocomplete similar to the languages filter (and it also store to query string?)

**Comment by tn5421** [comment]
I, personally, would like this feature so I can find cool communities that are not on the big 5 or so instances (lemmy.ml, lemmy.world, beehaw.org, sh.itjust.works, feddit.de)

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/1da1774e-75e4-4cbb-81f9-fccb0280814e)

mocked this up tonight, works pretty well for what you were thinking.

will merge soon™

**Comment by tgxn** [comment]
these should be live now - let me know if you have any other ideas 💭💭💭💯💯
