### ISSUE TITLE
Home instance doesn't work with kbin

### ISSUE THREAD

**Issue by pvmzqahgyd** [tgxn/lemmy-explorer#53]
When selecting kbin.social as a Home Instance, the generated links are not working, as kbin operates with /m/ instead of /c/ in the URL. So for example, the default generated https://kbin.social/**c**/applewatch@lemmy.world will not work, it needs to be generated as https://kbin.social/**m**/applewatch@lemmy.world

**Comment by tgxn** [comment]
Should I add support for kbin instances? - It is called Lemmyverse, after all...

However I'm thinking that since we can federate and interact with kbin users, it might be worthwhile showing a separate list of kbin communities?

I can see instances discovered using kbin versions, though I currently ignore them as their `software` is not `lemmy`. I'd need to look at the kbin API and determine how to crawl it.
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/927cd897-b677-4be8-99e6-1905ccde5141)

Questions
- How should the kbin communities be displayed? Alongside the lemmy communities? Seperately?
- For the "Home Instance" feature, this only supports setting yoru home instance, we don't know if it's a Lemmy or a kbin instance, so can;t set the URL based on that.

**Comment by ppptan** [comment]
I'd say that kbin magazines should be alongside the lemmy communities.  Would the url thing work if you provide a toggle choosing if your home instance is kbin or lemmy?

**Comment by tgxn** [comment]
Yep, that would solve the home instance links. (Y)

I'll have a play with their API tonight.

**Comment by ThornedRose** [comment]
A longer term solution suggestion: A different domain (something like threadiverse.net) that becomes the default that serves up both Lemmy and Kbin then set the current domain lemmyverse.net to hit the same site but filters only for Lemmy. Now, as a former website designer, I get this is a PITA and certainly costs more. But feels like it would capture more of the community.

From my personal view, I like Kbin's UI more than Lemmy. Also with Beehaw currently defederated from lemmy.world and lemmy.ml, I can't use my Beehaw or Lemmy World accounts to see all the communities I am subbed to. However I can with my Kbin account. This separation is annoying for finding more communities to sub to though. I can find Lemmy communities through Kbin's magazine search (this is a recent change) but I can't find Kbin magazines through Lemmy (including Lemmy Explorer). I find Lemmy Explorer the nicest to use to find new communities out of all the options though. But since it doesn't include Kbin, I still have to go elsewhere to find Kbin magazines.

Since we want to appeal to as many newcomers to the Fediverse as possible, having a one stop shop where you can find all ActivityPub (or at least 'Threadiverse' communities and instances) would make new user uptake much easier.

**Comment by fiskfisk33** [comment]
I would love for kbin, or any other compatible (if any) software were included.
I don't see why we should segregate, federation ftw

**Comment by pvmzqahgyd** [comment]
Hey @tgxn have you had a chance to give this a thought? I see Lemmy Explorer referenced quite often on kbin but then users abandon it as it doesn't work.

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/757522d9-5aad-48d7-a4da-591602336628)

Thinking something like this.

**Comment by tgxn** [comment]
Check it out 💯  https://lemmyverse.net/communities

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/73c22cd4-a219-4d88-beab-82c6d8dd6586)

Give it a test for me and spread the word if it's all good 😎

**Comment by pvmzqahgyd** [comment]
Works beautifully, thanks! I'll post on kbin asap

**Comment by tgxn** [comment]
please lmk if you got any more issues or have more ideas 💡⚡⚡

**Comment by pvmzqahgyd** [comment]
> please lmk if you got any more issues or have more ideas 💡⚡⚡

I do, add kbin instances & communities perhaps 🙃
