### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by tconroy** [tgxn/lemmy-explorer#84]
Hello! 👋 great work on Lemmy Explorer! This is really more of a question/request than an issue, but I was curious if the API is able/allowed to be used within other apps (ie as the search functionality in a lemmy client)?

**Comment by tgxn** [comment]
If you want you can download the `.json`s from here:
https://github.com/tgxn/lemmy-explorer/tree/main/frontend/public/data

Please don't hotlink them from the public site - as it's an AWS CloudFront Distribution, BW costs money.

https://github.com/tgxn/lemmy-explorer/blob/main/frontend/public/data/instance.full.json
https://github.com/tgxn/lemmy-explorer/blob/main/frontend/public/data/community.full.json
_(the .full. ones contains a full dump, instead of the website ones which are split into chunks)_

**Comment by tgxn** [comment]
I'm planning on putting the static dumps somewhere other than Git, since it's a bit of a waste of repo space storing every version of the data. Maybe GitHub Releases?

I'll update the [README.md](https://github.com/tgxn/lemmy-explorer#data) when I change this though.
